### PR TITLE
内存泄露和Log位置增加。

### PR DESCRIPTION
**Pull request by xlittle**
主要修复了spprintf，php_format_date 引起的内存泄露。
另外，日志添加了脚步名和当前行数
日志输出格式为：
XX/test3.php:2| error | 42925 | 1430927135.25 | 2015:05:06 23:45:35 | this is a error test by ::log
XX/test3.php 为全路径，2为第二行

### CODE REVIEW

**Comment by xlittle** [comment]
开启debug模式，PHP输出：

[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/github/SeasLog/SeasLog/seaslog.c(912) :  Freeing 0x106F3C260 (41 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/study/php/php-compile/php-5.6.6/main/spprintf.c(794) :  Freeing 0x106F3CCC8 (79 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
Last leak repeated 2 times
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/github/SeasLog/SeasLog/seaslog.c(973) :  Freeing 0x106F3CD70 (32 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/github/SeasLog/SeasLog/seaslog.c(976) :  Freeing 0x106F3CDE8 (32 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/github/SeasLog/SeasLog/seaslog.c(977) :  Freeing 0x106F3CE60 (28 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/study/php/php-compile/php-5.6.6/Zend/zend_execute_API.c(841) :  Freeing 0x106F3CF90 (32 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/study/php/php-compile/php-5.6.6/ext/date/php_date.c(1207) :  Freeing 0x106F3D1B0 (79 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
Last leak repeated 1 time
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/github/SeasLog/SeasLog/seaslog.c(911) :  Freeing 0x106F3D3A8 (32 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/study/php/php-compile/php-5.6.6/main/spprintf.c(245) :  Freeing 0x106F3D4C8 (207 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
[Wed May  6 22:04:44 2015]  Script:  '/Users/xt/Zend/workspaces/module/test3.php'
/Users/xt/Documents/github/SeasLog/SeasLog/seaslog.c(974) :  Freeing 0x106F3D940 (7 bytes), script=/Users/xt/Zend/workspaces/module/test3.php
=== Total 13 memory leaks detected ===

**Comment by xlittle** [comment]
Seaslog 版本为1.1.8
系统环境:OS X 10.10.3
PHP : PHP 5.6.6 (cli) (DEBUG)

**Comment by Neeke** [comment]
感谢PR, 是否做过 5.3 \ 5.4 \ 5.5的测试 ?

另:  可将联系方式发到我的邮箱,方便沟通.   ciogao@gmail.com  或  neeke@php.net

**Comment by Neeke** [comment]
fixed this https://github.com/Neeke/SeasLog/commit/a32db359ef8d648fa0dd97ef310c32fdab0194ce

and add you into https://github.com/Neeke/SeasLog/blob/master/CREDITS

**Pull request closed without merging**
